name: hola-mundo
on: [push]
jobs:
  hola-mundo-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: run index
        run: node index.js